# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

# Production stage
FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/package.json ./

COPY --from=builder /app/pnpm-lock.yaml ./

RUN pnpm install --prod

ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "run", "start"]