services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ghcr.io/suman-webgendev/stream-mern:backend-latest
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ghcr.io/suman-webgendev/stream-mern:frontend-latest
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - server
